name: find_a_bro
description: Flutter UI for a find a bro application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_map: ^5.0.0
  graphql_flutter: ^5.2.0-beta.5
  latlong2: ^0.9.0
  open_route_service: ^1.2.3
  provider: ^6.0.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.1.1

flutter:
  uses-material-design: true
  assets: 
    - assets/
